#debug: true
server:
  # undertow
  undertow:
    accesslog:
      dir: ./log/ # Undertow access log directory.
      enabled: false # Enable access log.
      pattern: '%t [%I] %a %r %s (%b Byte) (%T ms)' # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
    buffer-size: # Size of each buffer in bytes.
    #buffers-per-region: # Number of buffer per region.
    direct-buffers: # Allocate buffers outside the Java heap.
    io-threads: # Number of I/O threads to create for the worker.
    max-http-post-size: 0 # Maximum size in bytes of the HTTP post content.
    worker-threads: # Number of worker threads.
  port: 8080
  servlet.context-path: /SpringbootDemo/

# 配置spring
spring:
  # 配置运行时使用的配置文件 dev|test|pro
  profiles:
    active: dev
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
    max-file-size: 500MB
    max-request-size: 500MB
    enabled: true
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/


# #配置视图解析器
#spring:thymeleaf:
#  # 检查模板是否存在，然后再呈现
#  check-template-location: true
#  # 在构建URL时预先查看名称的前缀
#  prefix: classpath:/templates/
#  # 构建URL时附加查看名称的后缀.
#  suffix: .html
#  # 链中模板解析器的顺序
#  template-resolver-order: 0
#  encoding: UTF-8
#  content-type: text/html
#  mode: HTML5
#  cache: false
#thymeleaf end

logging:
  level:
    com.ibatis: DEBUG
    org.springframework.web: DEBUG
    priv.zsk.springbootdemo: DEBUG



# Mybatis配置
#由于mybatis plus使用多数据源的时候会倒是yml配置文件里面的配置失效，
#所以使用javaconfig的方式配置，又因为牵涉到动态数据的问题，
#所以将有关mybatis plus的相关配置放到了DynamicDataSourceConfig.java中。

#mybatis
#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.winnerdt.modules.*.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    # Sequence序列接口实现类配置
#    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 0
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器(从mybatis-plus3.XX以后不支持这种方式配置注入器，这里通过com.winnerdt.config.MySqlInjector进行配置)
##    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true

