classmanager:
  upload:
    dir: data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=true&verifyServerCertificate=false&allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: admin
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
