#debug: true
server:
  # undertow
  undertow:
    accesslog:
      dir: ./log/ # Undertow access log directory.
      enabled: false # Enable access log.
      pattern: '%t [%I] %a %r %s (%b Byte) (%T ms)' # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
    buffer-size: # Size of each buffer in bytes.
    #buffers-per-region: # Number of buffer per region.
    direct-buffers: # Allocate buffers outside the Java heap.
    io-threads: # Number of I/O threads to create for the worker.
    max-http-post-size: 0 # Maximum size in bytes of the HTTP post content.
    worker-threads: # Number of worker threads.
  port: 8080
  servlet.context-path: /SpringbootDemo/

# 配置spring
spring:
  # 配置运行时使用的配置文件 dev|test|pro
  profiles:
    active: dev
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
    max-file-size: 500MB
    max-request-size: 500MB
    enabled: true
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/
 #配置视图解析器
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

logging:
  level:
    com.ibatis: DEBUG
    org.springframework.web: DEBUG
    priv.zsk.springbootdemo: DEBUG



# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
